// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-locale';
export { Provider, useModel } from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-access/types.d';
export * from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-antd/types.d';
export * from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'I:/code/rust/umi_gitee/rust-tauri-umi/node_modules/.pnpm/@umijs+renderer-react@4.6.2_031ce76bd072575f474afb3c4c4bdad4/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'I:/code/rust/umi_gitee/rust-tauri-umi/node_modules/.pnpm/@umijs+renderer-react@4.6.2_031ce76bd072575f474afb3c4c4bdad4/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'I:/code/rust/umi_gitee/rust-tauri-umi/node_modules/.pnpm/umi@4.6.25_@babel+core@7.28_128041de3ace62e8b32adf2c39e8421f/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
