// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","redirect":"/signIn","parentId":"1","id":"2"},"3":{"name":"menu.fakeHome","path":"/fakeHome","parentId":"1","id":"3"},"4":{"path":"/fakeHome","redirect":"/fakeHome/settings","parentId":"3","id":"4"},"5":{"name":"menu.settings","path":"/fakeHome/settings","parentId":"3","id":"5"},"6":{"name":"menu.home","path":"/home","parentId":"1","id":"6"},"7":{"path":"/home","redirect":"/home/chats","parentId":"6","id":"7"},"8":{"name":"menu.settings","path":"/home/settings","parentId":"6","id":"8"},"9":{"name":"menu.chats","path":"chats","parentId":"6","id":"9"},"10":{"path":"","redirect":"dashboard","parentId":"9","id":"10"},"11":{"name":"menu.chats.chat","path":"chat","parentId":"9","id":"11"},"12":{"name":"menu.chats.dashboard","path":"dashboard","parentId":"9","id":"12"},"13":{"name":"menu.contacts","path":"contacts","parentId":"6","id":"13"},"14":{"path":"","redirect":"dashboard","parentId":"13","id":"14"},"15":{"name":"menu.contacts.dashboard","path":"dashboard","parentId":"13","id":"15"},"16":{"name":"menu.contacts.friend","path":"friend","parentId":"13","id":"16"},"17":{"name":"menu.access","path":"/access","parentId":"1","id":"17"},"18":{"name":"menu.signIn","path":"/signIn","parentId":"1","id":"18"},"19":{"name":"menu.signUp","path":"/signUp","parentId":"1","id":"19"},"20":{"name":"menu.testComponent","path":"/testComponent","parentId":"1","id":"20"},"21":{"path":"/media/handler","id":"21"},"22":{"path":"/media/videoCall","id":"22"},"23":{"path":"/search/friend","id":"23"},"24":{"path":"/*","id":"24"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__RootLayout" */'@/layouts/RootLayout.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__FakeLayout__index" */'@/layouts/FakeLayout/index.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Home__Settings__index" */'@/pages/Home/Settings/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "layouts__HomeLayout__index" */'@/layouts/HomeLayout/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Home__Settings__index" */'@/pages/Home/Settings/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "layouts__HomeLayout__ChatsLayout__index" */'@/layouts/HomeLayout/ChatsLayout/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Home__Chats__Chat__index" */'@/pages/Home/Chats/Chat/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Home__Chats__Dashboard__index" */'@/pages/Home/Chats/Dashboard/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "layouts__HomeLayout__ContactsLayout__index" */'@/layouts/HomeLayout/ContactsLayout/index.tsx')),
'14': React.lazy(() => import('./EmptyRoute')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Home__Contacts__components__Dashboard" */'@/pages/Home/Contacts/components/Dashboard.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Home__Contacts__index" */'@/pages/Home/Contacts/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Access__index" */'@/pages/Access/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Sign__SignIn__index" */'@/pages/Sign/SignIn/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__Sign__SignUp__index" */'@/pages/Sign/SignUp/index.tsx')),
'20': React.lazy(() => import(/* webpackChunkName: "p__TestComponent__index" */'@/pages/TestComponent/index.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__Media__Handler__index" */'@/pages/Media/Handler/index.tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__Media__VideoCall__index" */'@/pages/Media/VideoCall/index.tsx')),
'23': React.lazy(() => import(/* webpackChunkName: "p__Search__Friend__index" */'@/pages/Search/Friend/index.tsx')),
'24': React.lazy(() => import(/* webpackChunkName: "p__Error__index" */'@/pages/Error/index.tsx')),
},
  };
}
