// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/models/global';
import model_2 from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/models/p2pVideoConfig';
import model_3 from 'I:/code/rust/umi_gitee/rust-tauri-umi/apps/pc/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: 'p2pVideoConfig', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
